PKGDIR=../..
<$PKGDIR/mkconfig


DIRS=\
	t\

<$MKFILES/mksubdirs


DISBIN=$PKGDIR/dis/lib

TARG=\
	tap.dis\

SYSMODULES=\
	sys.m\
	draw.m\
	debug.m\

OPTMODULES=\

MODULES=\
	$PKGDIR/module/tap.m\

<$MKFILES/mkdis
