<../../../mkconfig

TARG=\

TESTS=\
	smoke.dis\
	smoke2.dis\

SYSMODULES=\
	sys.m\
	draw.m\

MODULES=\
	../../../module/t.m\
	../../../module/tap.m\

<../../../mktest
LIMBOFLAGS=$LIMBOFLAGS -I../../../../../../
