OPT_ROOT=$INFERNO_HOME
<../../../mkconfig

TARG=\

TESTS=\
	smoke.dis\

SYSMODULES=\
	sys.m\
	draw.m\

MODULES=\
	../../../module/t.m\
	../../../module/tap.m\

<../../../mktest
LIMBOFLAGS=$LIMBOFLAGS -I$OPT_ROOT
